=== puolimatkankrouvi/xml/catalog.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.0" vc:maxVersion="1.1">

<xs:simpleType name="money">
  <xs:restriction base="xs:decimal">
    <xs:fractionDigits value="2">
  </xs:restriction>

</xs:simpleType>

<xs:element name="catalog">
  <xs:complexType>
    <xs:sequence>
    
      <xs:element name="title" type="xs:string"></xs:element>
      <xs:element name="introduction">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="para" type="xs:string" minOccurs="1" maxOccurs="unbounded">
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      
      <xs:element name="product">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="title" type="xs:string"></xs:element>
            <xs:element name="description">
              <xs:complexType>
                <xs:element name="para" type="xs:string">
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="xs:string" use="required"> </xs:attribute>
          <xs:attribute name="price" type="money" use="optional" > </xs:attribute>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  
  </xs:complexType>
</xs:element>

=== puolimatkankrouvi/xml/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="catalog.xsd">
  <title>Outdoor products</title>
  <introduction>
    <para>We offer a great variety of basic stuff for mountaineering
          such as ropes, harnesses and tents.</para>
    <para>Our shop is proud for its large number of available
      sleeping bags.</para>
  </introduction>
  <product id="x-223">
    <title>Multi freezing bag  Nightmare camper</title>
    <description>
      <para>You will feel comfortable till  minus 20 degrees - At
            least if you are a penguin or a polar bear.</para>
    </description>
  </product>
  <product id="r-334">
    <title>Rope 40m</title>
    <description>
      <para>Excellent for indoor climbing.</para>
    </description>
  </product>
</catalog>
